spring.application.name=taskmaster
server.port=8081
# spring.profiles.active=h2
# ou
spring.profiles.active=mysql

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=500MB

server.tomcat.connection-timeout=60000ms
server.tomcat.max-swallow-size=104857600


